-- 1:
BEGIN
NULL;
END;

--2
BEGIN
    DBMS_OUTPUT.PUT_LINE('HELLO WORLD');
END;

-- 3:

SELECT  KEYWORD FROM V$RESERVED_WORDS WHERE LENGTH = 1 AND KEYWORD != 'A';

-- 4:

SELECT  KEYWORD FROM V$RESERVED_WORDS WHERE LENGTH > 1 AND KEYWORD != 'A' ORDER BY KEYWORD;

--5.1

DECLARE  X NUMBER(5) := 5;
  Y NUMBER(10,2) := 10.5;
  Z NUMBER(10,2);
BEGIN
DBMS_OUTPUT.PUT_LINE('X = ' || x);
DBMS_OUTPUT.PUT_LINE('Y = ' || Y);
Z:= X + Y;
DBMS_OUTPUT.PUT_LINE('X+Y =  '|| Z ||'');
Z:= X - Y;
DBMS_OUTPUT.PUT_LINE('X-Y =  '|| Z ||'');
Z:= Y / X;
DBMS_OUTPUT.PUT_LINE('Y / X =  '|| Z ||'');
END;
