

ALTER SESSION SET "_oracle_script" = TRUE; 
-- 1.

create tablespace TS_LVO
datafile 'C:\Tablecpaces\Lab2\ts_lvo.dbf'
size 7M
autoextend on next 5M
maxsize 30M
extent management local;

-- 2:
create temporary tablespace TS_LVO_TEMP
tempfile 'C:\Tablecpaces\Lab2\ts_lvo_temp.dbf'
size 5M
autoextend on next 3M
maxsize 20M
extent management local;

-- 3:
select TABLESPACE_NAME, STATUS , contents logging from SYS.DBA_TABLESPACES;

-- 4:
select TABLESPACE_NAME,STATUS,MAXBYTES,USER_BYTES,FILE_NAME from DBA_DATA_FILES
UNION
select TABLESPACE_NAME,STATUS,MAXBYTES,USER_BYTES,FILE_NAME from DBA_TEMP_FILES;

drop tablespace TS_LVO;
drop tablespace TS_LVO_TEMP;

-- 5:

CREATE ROLE c##rl_lvocore;

-- 6:
select * from DBA_ROLES where role like '%LVO%';

GRANT 
CREATE SESSION,
CREATE TABLE,
ALTER ANY TABLE,
DROP ANY TABLE,
CREATE VIEW,
DROP ANY VIEW,
CREATE PROCEDURE,
ALTER ANY PROCEDURE,
DROP ANY PROCEDURE
TO rl_lvocore;

-- 7:
SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE = 'RL_LVOCORE';

-- 7:
SELECT PRIVILEGE FROM DBA_SYS_PRIVS;
SELECT GRANTEE FROM DBA_SYS_PRIVS;
DROP ROLE c##rl_lvocore;

-- 8: 

CREATE PROFILE PF_LVOCORE LIMIT
    PASSWORD_LIFE_TIME 180
    SESSIONS_PER_USER 3
    FAILED_LOGIN_ATTEMPTS 7
    PASSWORD_LOCK_TIME 1
    PASSWORD_REUSE_TIME 10
    PASSWORD_GRACE_TIME DEFAULT
    CONNECT_TIME 180
    IDLE_TIME 30;
-- 9:
SELECT RESOURCE_NAME,RESOURCE_TYPE,LIMIT,COMMON,PROFILE FROM DBA_PROFILES;

-- 10:
SELECT * FROM DBA_PROFILES WHERE PROFILE = 'PF_LVOCORE';

-- 11:
SELECT * FROM DBA_PROFILES WHERE PROFILE = 'DEFAULT';
DROP PROFILE PF_LVOCORE;
-- 12:
CREATE USER LVOCORE IDENTIFIED BY 2025
DEFAULT TABLESPACE TS_LVO 
TEMPORARY TABLESPACE TS_LVO_TEMP
PROFILE PF_LVOCORE
ACCOUNT UNLOCK
PASSWORD EXPIRE;

GRANT rl_lvocore TO LVOCORE;
-- Obobad12345
--16:
ALTER USER LVOCORE QUOTA 2M ON TS_LVO;
-- 18:
ALTER TABLESPACE TS_LVO  OFFLINE;
-- 19:
ALTER TABLESPACE TS_LVO ONLINE;

DROP USER LVOCORE CASCADE;

DROP TABLE LVO_T_TEST;


