-- 1:

select TABLESPACE_NAME,CONTENTS LOGGING from SYS.DBA_TABLESPACES;

-- 2:

SELECT TABLESPACE_NAME,STATUS,MAXBYTES,USER_BYTES,FILE_NAME FROM DBA_DATA_FILES
UNION
SELECT TABLESPACE_NAME,STATUS,MAXBYTES,USER_BYTES,FILE_NAME FROM DBA_TEMP_FILES;

SELECT * FROM DBA_UNDO_EXTENTS;

-- 3:
SELECT * FROM V$LOG;
-- 4:
SELECT * FROM V$LOGFILE;
-- 5:
ALTER SYSTEM SWITCH LOGFILE;
-- 6:
/*Создайте дополнительную группу журналов повтора с
тремя файлами журнала. Убедитесь в наличии группы и файлов, 
а также в работоспособности группы (переключением).
Проследите последовательность SCN. */

ALTER DATABASE ADD LOGFILE GROUP 4 'C:\OracleDB\oradata\ORCL\REDO41.LOG' SIZE 50m BLOCKSIZE 512;
ALTER DATABASE ADD LOGFILE MEMBER 'C:\OracleDB\oradata\ORCL\REDO42.LOG' TO GROUP 4;
ALTER DATABASE ADD LOGFILE MEMBER 'C:\OracleDB\oradata\ORCL\REDO43.LOG' TO GROUP 4;

-- 7:
/*
Удалите созданную группу журналов повтора. 
Удалите созданные вами файлы журналов на сервере.
*/
ALTER DATABASE DROP LOGFILE MEMBER 'C:\OracleDB\oradata\ORCL\REDO43.LOG';
ALTER DATABASE DROP LOGFILE MEMBER 'C:\OracleDB\oradata\ORCL\REDO42.LOG';
--ALTER DATABASE DROP LOGFILE MEMBER 'C:\OracleDB\oradata\ORCL\REDO41.LOG';

ALTER DATABASE DROP LOGFILE GROUP 4;

-- 8:
SELECT NAME,LOG_MODE,OPEN_MODE,remote_archive FROM V$DATABASE;
SELECT instance_NAME,ARCHIVER,ACTIVE_STATE FROM V$INSTANCE;

-- 9:
SELECT * FROM V$ARCHIVED_LOG;

SELECT * FROM DICTIONARY WHERE TABLE_NAME LIKE '%ARCHIVE%';

-- 10 SQL PLUS
SELECT NAME,LOG_MODE FROM V$DATABASE;
SELECT instance_NAME,ARCHIVER,ACTIVE_STATE FROM V$INSTANCE;
SELECT * FROM V$LOG;
SELECT * FROM V$LOGFILE;

-- 11:
ALTER SYSTEM SWITCH LOGFILE;
SELECT * FROM V$ARCHIVED_LOG;
ARCHIVE LOG LIST;
-- 12:
SELECT NAME,LOG_MODE FROM V$DATABASE;
-- 13:
SELECT * FROM v$controlfile;
-- 14:
SHOW PARAMETER CONTROL;
SELECT * FROM v$controlfile_record_section;
ALTER DATABASE BACKUP CONTROLFILE TO TRACE AS 'C:\BackUp\trace.txt';


